version: '3.8'

services:
  # PostgreSQL Database
  aroma-app-db:
    image: postgres:15
    container_name: aroma-app-db
    environment:
      POSTGRES_DB: aroma_app_db
      POSTGRES_USER: pyme_user
      POSTGRES_PASSWORD: pyme_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pyme_user -d aroma_app_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  # pgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - aroma-app-db
    restart: unless-stopped

volumes:
  postgres_data: 