[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
FLASK_ENV = "production"
RENDER = "true"
DATABASE_URL = "sqlite:///pyme_app.db"
SECRET_KEY = "your-secret-key-change-in-production" 