# Dockerfileを使わない場合（推奨）
[build]
builder = "nixpacks"

# Dockerfileを使用する場合（コメントアウト）
# [build]
# builder = "dockerfile"
# dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[deploy.envs]
FLASK_ENV = "production"
RENDER = "true"
DATABASE_URL = "sqlite:///pyme_app.db"
SECRET_KEY = "your-secret-key-change-in-production"
PYTHON_VERSION = "3.11.9"